### ISSUE TITLE
Can you extract skill effect images, I want to use u3d to rewrite the game client

### ISSUE THREAD

**Issue by yinhe14** [SoulsaverX/SoulSaverX#5]
Can you extract the skill effect pictures, the spr parser can't get the skill effect related pictures, as long as I can extract these resources, I can use u3d to completely replicate this game

**Comment by sopanatx** [comment]
to extract the skill effect you should to use attack.csp file

**Comment by yinhe14** [comment]
Is there a relevant extraction tool?
